### ISSUE TITLE
[Request] security

### ISSUE THREAD

**Issue by Tcll** [clipr/clipr#2]
I actually had high hopes for this project and almost downloaded
but it's based on an insecure web language, and a memory-hogging API that's roughly no different from ActiveX

may I request porting to a more secure language like C++, as well as a more secure way to keep things in sync.
I would prefer the internet did not have uncontrolled open access to my LAN clipboard.

**Comment by zisismaras** [comment]
Hi,

I am no longer maintaining the project.
Feel free to fork and change it as you wish

Best
